language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
install:
  - yarn install
script:
  - yarn commitlint-travis
after_success:
  - yarn semantic-release
